version: 1.1
kind: operation
name: build-spacy-streamlit
params:
  destination:
    connection: CONNECTION_NAME
    value: polyaxon-examples:spacy-streamlit-demo
  context:
    value: "{{ globals.artifacts_path }}/spacy-streamlit-polyaxon-demo"
runPatch:
  init:
    - git:
        url: "https://github.com/rwatts3/spacy-streamlit-polyaxon-demo"
hubRef: kaniko
